-- Provider integrations for tracking/returns sync
-- Generated: 2026-02-23

create extension if not exists pgcrypto;

create table if not exists public.integration_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null check (provider in ('easypost', 'shopify', 'amazon_sp_api')),
  external_account_id text not null default '',
  display_name text,
  status text not null default 'active' check (status in ('active', 'paused', 'error')),
  config jsonb not null default '{}'::jsonb,
  secret jsonb not null default '{}'::jsonb,
  refresh_interval_minutes integer not null default 60 check (refresh_interval_minutes >= 5),
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists integration_accounts_user_provider_external_uidx
  on public.integration_accounts (user_id, provider, external_account_id);

create index if not exists integration_accounts_user_status_idx
  on public.integration_accounts (user_id, status);

create table if not exists public.integration_sync_runs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  integration_account_id uuid references public.integration_accounts(id) on delete set null,
  provider text not null,
  mode text not null check (mode in ('manual', 'open', 'scheduled', 'webhook')),
  status text not null check (status in ('started', 'success', 'error')),
  stats jsonb not null default '{}'::jsonb,
  error text,
  trigger_payload jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default timezone('utc', now()),
  finished_at timestamptz
);

create index if not exists integration_sync_runs_user_started_idx
  on public.integration_sync_runs (user_id, started_at desc);

create index if not exists integration_sync_runs_provider_started_idx
  on public.integration_sync_runs (provider, started_at desc);

create table if not exists public.integration_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  integration_account_id uuid references public.integration_accounts(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default timezone('utc', now()),
  processed_at timestamptz,
  process_error text
);

create unique index if not exists integration_webhook_events_provider_event_uidx
  on public.integration_webhook_events (provider, event_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_integration_accounts_updated_at on public.integration_accounts;
create trigger trg_integration_accounts_updated_at
before update on public.integration_accounts
for each row execute function public.set_updated_at();

alter table public.integration_accounts enable row level security;
alter table public.integration_sync_runs enable row level security;
alter table public.integration_webhook_events enable row level security;

-- Deny direct client access to sensitive integration tables.
-- Use Edge Functions with service role key to manage/sync integrations.
drop policy if exists integration_accounts_no_direct_access on public.integration_accounts;
create policy integration_accounts_no_direct_access
on public.integration_accounts
for all
to authenticated, anon
using (false)
with check (false);

drop policy if exists integration_sync_runs_no_direct_access on public.integration_sync_runs;
create policy integration_sync_runs_no_direct_access
on public.integration_sync_runs
for all
to authenticated, anon
using (false)
with check (false);

drop policy if exists integration_webhook_events_no_direct_access on public.integration_webhook_events;
create policy integration_webhook_events_no_direct_access
on public.integration_webhook_events
for all
to authenticated, anon
using (false)
with check (false);
